experiment_type: bleu_prediction
features_path: ../data/tatoeba_tf_train_thresh0.01.tsv
model:
  depth: 6
  iterations: 1330.0
  learning_rate: 0.12847446260906567
random_seed: 42
target_path: ../data/tatoeba_train_opus_scores.tsv
